In [5]:
import numpy as np
import pandas as pd

In [9]:
data = pd.read_csv('dataSet.csv')
type(data)

pandas.DataFrame

In [14]:
#to show top rows
data.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [15]:
#to show last selected rows
data.tail(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [17]:
data.shape

(636, 18)

In [19]:
data.info

<bound method DataFrame.info of       id  season       city        date                        team1  \
0      1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad
1      2    2017       Pune  2017-04-06               Mumbai Indians
2      3    2017     Rajkot  2017-04-07                Gujarat Lions
3      4    2017     Indore  2017-04-08       Rising Pune Supergiant
4      5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore
..   ...     ...        ...         ...                          ...
631  632    2016     Raipur  2016-05-22             Delhi Daredevils
632  633    2016  Bangalore  2016-05-24                Gujarat Lions
633  634    2016      Delhi  2016-05-25          Sunrisers Hyderabad
634  635    2016      Delhi  2016-05-27                Gujarat Lions
635  636    2016  Bangalore  2016-05-29          Sunrisers Hyderabad

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field
633        Kolkata Knight Riders        Kolkata Knight Riders         field
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
631  normal           0  Royal Challengers Bangalore            0
632  normal           0  Royal Challengers Bangalore            0
633  normal           0          Sunrisers Hyderabad           22
634  normal           0          Sunrisers Hyderabad            0
635  normal           0          Sunrisers Hyderabad            8

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
631               6         V Kohli
632               4  AB de Villiers
633               0    MC Henriques
634               4       DA Warner
635               0     BCJ Cutting

                                                venue          umpire1  \
0           Rajiv Gandhi International Stadium, Uppal      AY Dandekar
1             Maharashtra Cricket Association Stadium   A Nand Kishore
2              Saurashtra Cricket Association Stadium      Nitin Menon
3                              Holkar Cricket Stadium     AK Chaudhary
4                               M Chinnaswamy Stadium              NaN
..                                                ...              ...
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore
632                             M Chinnaswamy Stadium     AK Chaudhary
633                                  Feroz Shah Kotla        M Erasmus
634                                  Feroz Shah Kotla        M Erasmus
635                             M Chinnaswamy Stadium  HDPK Dharmasena

             umpire2  umpire3
0           NJ Llong      NaN
1             S Ravi      NaN
2          CK Nandan      NaN
3      C Shamshuddin      NaN
4                NaN      NaN
..               ...      ...
631     BNJ Oxenford      NaN
632  HDPK Dharmasena      NaN
633    C Shamshuddin      NaN
634        CK Nandan      NaN
635     BNJ Oxenford      NaN

[636 rows x 18 columns]>

In [21]:
data.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [23]:
data['winner']

0              Sunrisers Hyderabad
1           Rising Pune Supergiant
2            Kolkata Knight Riders
3                  Kings XI Punjab
4      Royal Challengers Bangalore
                  ...
631    Royal Challengers Bangalore
632    Royal Challengers Bangalore
633            Sunrisers Hyderabad
634            Sunrisers Hyderabad
635            Sunrisers Hyderabad
Name: winner, Length: 636, dtype: str

In [26]:
data[['team1', 'team2', 'winner']]

,team1,team2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore
633,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

In [35]:
data.iloc[0:10:2]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN

In [40]:
mask = data['city'] == 'Hyderabad'
data[mask].shape

(49, 18)

In [46]:
def get_match_count(city):
    mask = data['city'] == city
    return data[mask].shape[0]

In [47]:
get_match_count('Pune')

32